apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gloo-gateway-argo-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: gloo-mesh
    server: 'https://kubernetes.default.svc'
  project: default
  sources:
    - repoURL: https://storage.googleapis.com/gloo-platform/helm-charts
      targetRevision: 2.3.9
      helm:
        valueFiles:
        - $values/gloo-mesh/values/02-config-values.yaml
        parameters:
          - name: licensing.glooMeshLicenseKey
            value: ''
          - name: licensing.glooGatewayLicenseKey
            value: ''
      chart: gloo-platform
    - repoURL: https://github.com/ky-rafaels/gloo-platform-gitops.git 
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
